name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.18.0
      - uses: pnpm/action-setup@v4.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm i
        working-directory: ./packages/svelte-lexical
      - run: pnpm build
        working-directory: ./packages/svelte-lexical
      - run: pnpm check
        working-directory: ./packages/svelte-lexical
      - run: pnpm lint
        working-directory: ./packages/svelte-lexical

      - run: pnpm i
        working-directory: ./demos/playground
      - run: pnpm build
        working-directory: ./demos/playground
      - run: pnpm check
        working-directory: ./demos/playground
      - run: pnpm lint
        working-directory: ./demos/playground
      - run: pnpm size
        working-directory: ./demos/playground

      - run: pnpm i
        working-directory: ./demos/sveltekit
      - run: pnpm build
        working-directory: ./demos/sveltekit
      - run: pnpm check
        working-directory: ./demos/sveltekit
      - run: pnpm lint
        working-directory: ./demos/sveltekit

      - run: pnpm i
        working-directory: ./demos/richtext-editor
      - run: pnpm build
        working-directory: ./demos/richtext-editor
      - run: pnpm check
        working-directory: ./demos/richtext-editor
      - run: pnpm lint
        working-directory: ./demos/richtext-editor
      - run: pnpm size
        working-directory: ./demos/richtext-editor

      - run: pnpm i
        working-directory: ./demos/plaintext-editor
      - run: pnpm build
        working-directory: ./demos/plaintext-editor
      - run: pnpm check
        working-directory: ./demos/plaintext-editor
      - run: pnpm lint
        working-directory: ./demos/plaintext-editor
      - run: pnpm size
        working-directory: ./demos/plaintext-editor
