name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm i
        working-directory: ./packages/svelte-lexical
      - run: pnpm build
        working-directory: ./packages/svelte-lexical
      - run: pnpm svelte-check
        working-directory: ./packages/svelte-lexical
      - run: pnpm lint
        working-directory: ./packages/svelte-lexical

      - run: pnpm i
        working-directory: ./demos/playground
      - run: pnpm build
        working-directory: ./demos/playground
      - run: pnpm svelte-check
        working-directory: ./demos/playground
      - run: pnpm lint
        working-directory: ./demos/playground

      - run: pnpm i
        working-directory: ./demos/sveltekit
      - run: pnpm build
        working-directory: ./demos/sveltekit
      - run: pnpm svelte-check
        working-directory: ./demos/sveltekit
      - run: pnpm lint
        working-directory: ./demos/sveltekit

      - run: pnpm i
        working-directory: ./demos/richtext-editor
      - run: pnpm build
        working-directory: ./demos/richtext-editor
      - run: pnpm svelte-check
        working-directory: ./demos/richtext-editor
      - run: pnpm lint
        working-directory: ./demos/richtext-editor

      - run: pnpm i
        working-directory: ./demos/plaintext-editor
      - run: pnpm build
        working-directory: ./demos/plaintext-editor
      - run: pnpm svelte-check
        working-directory: ./demos/plaintext-editor
      - run: pnpm lint
        working-directory: ./demos/plaintext-editor
