name: Svelte Lexical Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'demos/plaintext-editor/**'
      - 'demos/richtext-editor/**'
      - 'demos/richtext-editor-basic/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'demos/plaintext-editor/**'
      - 'demos/richtext-editor/**'
      - 'demos/richtext-editor-basic/**'

jobs:
  e2e-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.8]
        browser: ['chromium', 'firefox']
        editor-mode: ['rich-text', 'plain-text']
        events-mode: ['legacy-events', 'modern-events']
    env:
      CI: true
      E2E_EDITOR_MODE: ${{ matrix.editor-mode }}
      E2E_EVENTS_MODE: ${{ matrix.events-mode }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      # - run: npm i -g npm@8
      #   working-directory: ./demos/playground
      # - uses: actions/cache@v3
      #   id: cache
      #   with:
      #     path: |
      #       node_modules
      #       C:\Users\runneradmin\AppData\Local\ms-playwright
      #     key: ${{ runner.os }}-v${{ secrets.CACHE_VERSION }}-${{ hashFiles('package-lock.json') }}
      # - name: Install dependencies
      #   if: steps.cache.outputs.cache-hit != 'true'
      - run: pnpm i
        working-directory: ./demos/playground
      - name: Download browsers
        run: pnpm playwright install
        working-directory: ./demos/playground
      - run: pnpm test-e2e-ci:${{ matrix.browser }}
        working-directory: ./demos/playground
      - name: Upload Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: ./demos/playground/playwright-report
          retention-days: 7